apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: iot-lab
spec:
  selector:
    app: kafka-connect
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 32257
  type: NodePort
