FROM confluentinc/cp-kafka-connect:7.5.0
COPY plugins/kafka-mqtt-source-connector /usr/share/java/plugins/kafka-mqtt-source-connector
COPY plugins/neo4j-kafka-connect-5.1.11 /usr/share/java/neo4j-kafka-connect-5.1.11

